### ISSUE TITLE
Not working for pages

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql-tax-query#10]
I have a custom taxonomy called `type`. It is used on `pages`. 

The below `taxQuery` doesn't work, it returns empty results. There are 11 pages in the `type` category with slug `latest`.

```
query{
  pages(
    where: {
      taxQuery: {
        taxArray: [
          {
            terms: ["latest"],
            taxonomy: TYPE,
            operator: IN,
            field: SLUG
          }
        ]
      }
  	}
  ){
    edges{
      cursor
      node{
        slug
        title
      }
    }
  }
}
```

And the results are:
```
{
  "data": {
    "pages": {
      "edges": []
    }
  }
}
```

**Comment by jasonbahl** [comment]
@drewbaker I just tried and this seems to work for me: 

```
{
  pages(
    where: {
        taxQuery: {
            taxArray: [
                {
                   taxonomy: CUSTOMTERM, 
                   terms: ["New Term"], 
                   field: NAME
                }
             ]
          }
       }
    ) {
    nodes {
      id
      link
      slug
    }
  }
}
```

----

Here's the steps I took:

**Register Custom Taxonomy connected to Pages:**

add_action( 'init', function() {

	register_taxonomy(
		'custom_tax',
		'page',
		array(
			'public'            => true,
			'hierarchical'      => false,
			'labels'            => array(
				'name'          => _x( 'Custom', 'post format' ),
				'singular_name' => _x( 'Custom', 'post format' ),
			),
			'query_var'         => true,
			'show_ui'           => true,
			'_builtin'          => true,
			'show_in_rest'      => true,
			'show_in_graphql'   => true,
			'graphql_single_name' => 'CustomTerm',
			'graphql_plural_name' => 'CustomTerms'
		)
	);
} );

**Comment by drewbaker** [comment]
Weird, this is totally not working for me. 

Do you see anything I am missing?

![Screen Shot 2019-05-06 at 1 30 17 PM](https://user-images.githubusercontent.com/475015/57253336-554f8b80-7003-11e9-89a8-c13caaea9ab7.png)
![Screen Shot 2019-05-06 at 1 30 11 PM](https://user-images.githubusercontent.com/475015/57253341-57b1e580-7003-11e9-8961-c7e009a9a1c8.png)
![Screen Shot 2019-05-06 at 1 30 35 PM](https://user-images.githubusercontent.com/475015/57253345-597ba900-7003-11e9-8770-5b699636b214.png)

**Comment by drewbaker** [comment]
For future people: So I spoke with Jason today and found a little hidden setting, by default all page queries have `parent: 0` set on them, so if you want any depth page, then you need to set `parent: null` in the where clause! This ended up working!
