### ISSUE TITLE
All taxonomy posts

### ISSUE THREAD

**Issue by forepointmc** [wp-graphql/wp-graphql-tax-query#14]
'terms' is a required field and doesn't accept wildcard, so how to get all of the posts under a taxonomy?

**Comment by jasonbahl** [comment]
@forepointmc how would you do this in WP_Query? If you can show an example I can help think of a way to do the same in WPGraphQL

**Comment by forepointmc** [comment]
Hi actually its taxonomy terms I'm trying to get. I can't find a way in wpgraphql to get the all the terms of a taxonomy like this function does:

$terms = get_terms( array(
    'taxonomy' => 'post_tag',
    'hide_empty' => false,
) );

**Comment by forepointmc** [comment]
I sorted it

query {
  yourtaxonomyname {
    edges {
      node {
        id
        name
      }
    }
  }
}

done!
