### ISSUE TITLE
Compatibility with core plugin

### ISSUE THREAD

**Issue by hatsumatsu** [wp-graphql/wp-graphql-tax-query#17]
Could you clarify the compatibility between the version of this addon and the wp-graphql core plugin? I was trying to make this work with `0.0.2` and `0.1.0` of the extension and version `0.3.4`, `0.3.5`, `0.3.8` and `0.4.0` of the core plugin but had no luck. The `taxQuery` field is not  showing up under `posts > where` :-(

**Comment by jasonbahl** [comment]
@hatsumatsu sorry for the delay. WPGraphQL v0.4.2 fixes this (https://github.com/wp-graphql/wp-graphql/pull/1039). There was a param needed to be passed through a filter that wasn't getting passed through properly.
